### ISSUE TITLE
WebDAV setup

### ISSUE THREAD

**Issue by Acentelles** [michaelmior/zotero-remarkable#2]
I'm getting this awful error message when fetching items from Zotero:

```
Fetching items from Zotero...
3 items found.
Processing item HDHYRZAB
  Downloading zip...
PHP Fatal error:  Uncaught ErrorException: Undefined offset: 1 in /home/alberto/personal/remarkable/zotero-remarkable/vendor/guzzlehttp/guzzle/src/Client.php on line 354 in /home/alberto/personal/remarkable/zotero-remarkable/zotero-remarkable.php:11
Stack trace:
#0 /home/alberto/personal/remarkable/zotero-remarkable/vendor/guzzlehttp/guzzle/src/Client.php(354): errHandle(8, 'Undefined offse...', '/home/alberto/p...', 354, Array)
#1 /home/alberto/personal/remarkable/zotero-remarkable/vendor/guzzlehttp/guzzle/src/Client.php(273): GuzzleHttp\Client->applyOptions(Object(GuzzleHttp\Psr7\Request), Array)
#2 /home/alberto/personal/remarkable/zotero-remarkable/vendor/guzzlehttp/guzzle/src/Client.php(125): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#3 /home/alberto/personal/remarkable/zotero-remarkable/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\Client->requestAsync('get', Object(GuzzleHttp\Psr7\Uri), Array)
#4 /home/alberto/personal/remarkable/zotero-remarkable/vendor/guzzlehttp/guzzle/src/Client. in /home/alberto/personal/remarkable/zotero-remarkable/zotero-remarkable.php on line 11
```

Any ideas why is it happening?

**Comment by Acentelles** [comment]
The reason it didn't work was because I had my WEBDAV credentials empty.

Once I set them, I get the following one:
```
Fetching items from Zotero...
3 items found.
Processing item HDHYRZAB
  Downloading zip...
PHP Fatal error:  Uncaught RuntimeException: Error creating resource: [message] fopen(HDHYRZAB.zip): failed to open stream: No such file or directory
[file] /home/alberto/personal/remarkable/zotero-remarkable/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 323 in /home/alberto/personal/remarkable/zotero-remarkable/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php:252
Stack trace:
#0 /home/alberto/personal/remarkable/zotero-remarkable/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(334): GuzzleHttp\Handler\StreamHandler->createResource(Object(Closure))
#1 /home/alberto/personal/remarkable/zotero-remarkable/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(51): GuzzleHttp\Handler\StreamHandler->createStream(Object(GuzzleHttp\Psr7\Request), Array)
#2 /home/alberto/personal/remarkable/zotero-remarkable/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(37): GuzzleHttp\Handler\StreamHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#3 /home/alberto/personal/remarkable/zotero-remarkable/ven in /home/alberto/personal/remarkable/zotero-remarkable/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 52
```

Is there any work around that does not involve Webdav?
